const express = require('express');
const router = express.Router();
const{registerUser,loginUser,logoutUser,verifyUser,getProfile,deleteAccount}= require('../controllers/authController');
const {auth} = require('../middlewares/auth');
router.post("/register",registerUser);
router.post("/login",loginUser);
router.post("/logout",logoutUser);
router.post("/verifyUser",verifyUser);
router.get("/:id",auth,getProfile);
router.delete("/:id",auth,deleteAccount);
module.exports=router;